# Generated by Django 4.0 on 2022-05-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/search?q=placeholder+food+images&client=ubuntu&channel=fs&tbm=isch&source=iu&ictx=1&vet=1&fir=r4MyYWa6UxepTM%252CDE59x2KNdrhkvM%252C_%253Bjal7CZrCohPPcM%252CSht218MD2XkntM%252C_%253B7K26ALkHdMGaaM%252CpW-HFWw0VNMbnM%252C_%253BcAtq_o3hdy3hOM%252CPAwBzaJSiNcWRM%252C_%253Bi4LWV8nsfF3pZM%252Cvm_HY1Gpe19S-M%252C_%253BKzlEw1u98W7EKM%252C75wDOX_EasD4oM%252C_%253B59Y8go7tPpJqKM%252C0k5rhoJHXvlkdM%252C_%253BbrvVOAlrbLzfVM%252CwjWTBq_jYqmdeM%252C_%253B_f-j934pbgJPIM%252Ce1j17iealMc86M%252C_%253B-fO_excvO9BrdM%252C0RuYXFRXZuB68M%252C_%253B3gu7rag2AQnNmM%252C7RPpozL6R3FwOM%252C_%253BtWHGFraLIpPmbM%252C-EYq4YMSSYYZMM%252C_%253BFqgiTtdteGma4M%252CNhlb63xefFds-M%252C_%253B5nsC28LDwnHlEM%252CDTuB0awS6s_LNM%252C_&usg=AI4_-kS4Uy0trVJ_UU2EfRNF_SnuhXfZKQ&sa=X&ved=2ahUKEwiA8ougu_T3AhWP7XMBHSb5CT0Q9QF6BAgDEAE#imgrc=r4MyYWa6UxepTM', max_length=500),
        ),
    ]
