# Generated by Django 4.0 on 2022-06-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='user_name',
        ),
    ]
